language: node_js
node_js:
#  - "node"
  - "7"
#  - "6"
#  - "5"
#  - "4"
install:
  - true
script:
  - true
deploy:
  provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "nervous-efficient-rebel"
  key: latest/MyApp.zip
  application: nervous-efficient-rebel-app
  deployment_group: nervous-efficient-rebel-depgrp
  on:
    branch: develop
branches:
  except:
    - /v\d+\.\d+\.\d+/
notifications:
  email: false

