language: node_js
node_js:
#  - "node"
  - "7"
#  - "6"
#  - "5"
#  - "4"
install:
  - true
script:
  - true
after_script:
  - zip -r deploy * && mkdir deploy && mv deploy.zip deploy/
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: deploy
    skip_cleanup: true
    bucket: nervous-efficient-rebel
    region: eu-west-1
    on: &2
      branch: develop
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    key: deploy.zip
    bundle_type: zip
    bucket: nervous-efficient-rebel
    application: nervous-efficient-rebel-app
    deployment_group: nervous-efficient-rebel-depgrp
    region: eu-west-1
    wait-until-deployed: true
    on: *2

branches:
  except:
    - /v\d+\.\d+\.\d+/
notifications:
  email: false

