language: node_js
node_js:
  - "node"
  - "7"
  - "6"
install:
  - yarn install
script:
  - npm run unit-cover
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - git archive -o nervous-efficient-rebel.zip HEAD
  - mkdir deploy
  - mv nervous-efficient-rebel.zip deploy/
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: deploy
    skip_cleanup: true
    bucket: nervous-efficient-rebel
    region: eu-west-1
    on: &2
      branch: develop
      condition: $TRAVIS_NODE_VERSION = 7
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    key: nervous-efficient-rebel.zip
    bundle_type: zip
    bucket: nervous-efficient-rebel
    application: nervous-efficient-rebel-app
    deployment_group: nervous-efficient-rebel-depgrp
    region: eu-west-1
    wait-until-deployed: true
    on: *2

branches:
  except:
    - /v\d+\.\d+\.\d+/
notifications:
  email: false

