version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/ner/deploy

permissions:
  - object: /home/ec2-user/ner/deploy/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 777

hooks:
#  ApplicationStop:
#    - location: systemctl stop ner
#      timeout: 20
#      runas: ec2-user
#

  BeforeInstall:
    - location: deploy-bin/remove-deploy-folder.sh
      timeout: 20
      runas: ec2-user

  AfterInstall:
    - location: deploy-bin/post-deploy-install.sh
      timeout: 600
      runas: ec2-user

#  ApplicationStart:
#    - location: systemctl start ner
#      timeout: 20
#      runas: ec2-user
#
