version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/ner/deploy

permissions:
  - object: /home/ec2-user/ner/deploy/stanford-ner/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 1775
  - object: /home/ec2-user/ner/deploy/deploy-bin/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 1774
  - object: /home/ec2-user/ner/deploy
    pattern: "*"
    owner: ec2-user
    group: ec2-user
    mode: 774


hooks:
#  ApplicationStop:
#    - location: systemctl stop ner
#      timeout: 20
#      runas: ec2-user
#

  AfterInstall:
    - location: deploy-bin/post-deploy-install.sh

#  ApplicationStart:
#    - location: systemctl start ner
#      timeout: 20
#      runas: ec2-user
#
