version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/ner/nervous-efficient-rebel

permissions:
  - object: /home/ec2-user/ner/
    pattern: "nervous-efficient-rebel"
    owner: ec2-user
    group: ec2-user
    mode: 775

  - object: /home/ec2-user/ner/nervous-efficient-rebel/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 775

hooks:
  #ApplicationStop:
  #  - location: deploy-hooks/application-stop.sh
  #    timeout: 20

  AfterInstall:
    - location: deploy-hooks/after-install.sh
      timeout: 900

  ApplicationStart:
    - location: deploy-hooks/application-start.sh
      timeout: 20

  ValidateService:
    - location: deploy-hooks/validate-service.sh
      timeout: 20
